# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: reporter recheck requested
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because 60 days have passed
  with no response to a request that the reporter recheck oce.  A
  developer has judged the issue to have been addressed, so this issue will be
  closed automatically soon.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed, due to inactivity. If you think the issue has
  not been addressed properly, please reopen the issue, adding a comment that
  explains what you think remains to be done. Thanks!
