# Number of days of inactivity before an issue becomes stale
daysUntilStale: 56
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because 8 weeks have passed
  with no activity. (Adding the 'pinned' label will prevent this issue from ever
  going stale.)
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed because it has been stale for two weeks. If the
  reporter or one of the developers thinks that the issue has not been
  addressed properly, then they are asked to reopen it, ideally adding a
  comment that sheds more light on the matter.

