language: r
warnings_are_errors: false
sudo: required
dist: trusty

addons:
    apt:
        packages:
            - libgdal-dev
            - libproj-dev
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - devtools
    - rgdal
    - ncdf4
    - covr
env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False
        - _R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
        - _R_CHECK_TIMINGS_="0"

after_success:
        - Rscript -e 'library(covr); codecov(type="all")'

