language: r
warnings_are_errors: false
sudo: required
dist: trusty

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

addons:
    apt:
        packages:
            - libgdal-dev
            - libproj-dev
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - devtools
    - rgdal
    - ncdf4
    - covr
env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False

after_success:
        - Rscript -e 'library(covr); codecov(type="all")'

