on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # using and old version of pandoc to get around a bug:
      # https://stackoverflow.com/questions/67004645/r-knitting-error-rticles-vadjust-in-vertical-mode
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.11.4'
      - name: Install packages
        run: |
          install.packages("oce")
        shell: Rscript {0}

      - name: Build paper
        run: |
          rmarkdown::render("paper.Rmd")
          print(list.files())
        shell: Rscript {0}

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: inst/joss/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
            name: paper
            # This is the output path where Pandoc will write the compiled
            # PDF. Note, this should be the same directory as the input
            # paper.md
            path: inst/joss/paper.pdf

